l=[
    {
        'name':'chethana',
        'followers':50
    },
    {
        'name':'bunny',
        'followers':90
    },
    {
        'name':'ramu',
        'followers':80
    },
    {
        'name':'sanvi',
        'followers':70
    },
    {
        'name':'sayooj',
        'followers':65
    },
    {
        'name':'vantara',
        'followers':500
    },
    {
        'name':'politician',
        'followers':600
    },
    {
        'name':'Actor',
        'followers':700
    },
    {
        'name':"popstar",
        'followers':800
    }
]